### PR TITLE
Cpplint integration

### PR DESCRIPTION
**Pull request by Xav83**
Based on #38.

Integrates the static analyzer tool [cpplint](https://github.com/cpplint/cpplint) to the tools used to analyze the C++ code (with clang-tidy, cppcheck and include-what-you-use).

With this tool, the goal is to make the code follow a standard and make it more readable.

@Riuzakiii There is the last element mentioned by `cpplint` for the files of the project about copyright message:
```
No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
```
Is it OK for you if I add the comment `// Copyright 2022 Riuzakiii` on top of the cpp files to make the code comply to all the `cpplint` messages ?

### CODE REVIEW

**Comment by Riuzakiii** [comment]
@Xav83 I don't see any issue for adding the copyright mention on top of the files

**Review by Riuzakiii — CHANGES_REQUESTED** [review]
Is there a way to keep cpplint without the formatting part ? I don't really like the cpplint formatting and it is also strange to have two formatting checks 😕 what is your opinion on this ?

**Comment by Xav83** [comment]
@Riuzakiii Now this PR integrates cpplint, but don't inforce anything on the formatting. You will be able to look at the output with running with the static analysis check activated, to see which element you want to integrate or not :wink:

**Review by Riuzakiii — APPROVED** [review]
looks great 👍

**Pull request merged**
