### PR TITLE
Improves Xcode versions support on Azuze Pipelines

### PR DESCRIPTION
**Pull request by Xav83**
This PR is based on #8.

The purpose of this Pull Request is to configure Azuze Pipelines in order to check a maximum of configuration on OSX, with Xcode, to compile the project.

## Lists of all the versions of Xcode depending on the OSX version
- [**MacOs 10.15**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) : Xcode 10.3, 11.2.1, 11.3.1, 11.4.1, 11.5, 11.6, 11.7 12.0.1, 12.1, 12.2, 12.3, 12.4
- [**MacOs 11**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) : Xcode 11.7, 12.4, 12.5.1, 13.0, 13.1, 13.2, 13.2.1
- [**MacOS 12**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode) : Xcode 13.1, 13.2.1, 13.3.1, 13.4

TODO:
- [X] Lists all the versions of Xcode available on each OSX version available on Azure Pipelines
- [X] Adds one job for each Xcode version avalable on each OSX version available on Azure Pipelines

### CODE REVIEW

**Review by Riuzakiii — COMMENTED** [review]
61 checks seem to be a bit much, maybe having only the latest Xcode version for each platform could be enough ?

**Comment by Xav83** [comment]
Indeed, @Riuzakiii , this is probably too much :laughing: 
We can reduce the number of configuration without problem (I will probably only comment the ones we don't want, in order to easily add them again, if someone ever has an issue in one of them :wink: 

To be sure that I understood the configurations you want to keep (cf. [GitHub discussion](https://github.com/Riuzakiii/XYModem/discussions/1#discussioncomment-2786396)), the configuration we are going to keep are the following one:
- [**MacOs 10.15**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) : Xcode 10.3, 11.7 and 12.4
- [**MacOs 11**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) : Xcode 11.7, 12.5.1 and 13.2.1
- [**MacOS 12**](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode) : Xcode 13.4

And in a future Pull Request, we will add the other 2:
- Xcode 13.4 (AppleClang) for arm64 architectures (targeting Apple M1) (debug and release)
- clang 14 on Ubuntu 22.04 (debug and release) https://packages.ubuntu.com/jammy/clang

**Comment by Riuzakiii** [comment]
I would even reduce it to 

[MacOs 10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) : Xcode 12.4
    [MacOs 11](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) : Xcode 13.2.1
    [MacOS 12](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode) : Xcode 13.4

This way, we would support any recent apple computer assuming the system has been kept up-to-date and the xcode version is the latest available for the macos version (which it should). Older devices might still be in use but let's wait for user requests if someone needs this.

**Comment by Xav83** [comment]
Seems nice to me ! :slightly_smiling_face: 
I will adapt this PR tomorrow then :wink:

**Review by Riuzakiii — APPROVED** [review]
LGTM :)

**Pull request merged**
